### ISSUE TITLE
Please stop polute global scope

### ISSUE THREAD

**Issue by stalkerg** [Blankeos/dot.js#4]
For modern ES lib it's absolutely wrong behavior https://github.com/Blankeos/tsdot/blob/main/src/index.ts#L233 
it's should be enabled optional during bundling process.

**Comment by Blankeos** [comment]
Thanks for the comment. Wasn't aware that it was widely considered wrong.

I was just trying to keep the old behavior when importing it via a <script /> tag in Vanilla HTML.

I'll make a way to make it optional. Thanks!

**Comment by stalkerg** [comment]
> I was just trying to keep the old behavior when importing it via a <script /> tag in Vanilla HTML.

Yes, I think it's good point, but I believe it should be enabled only during bundle browser stand alone script. For ES6 or TS module it shouldn't be enabled.
